Controllers/Finance/MasterInfo/CashAgainstSaleController.cs
using Exampler_ERP.Models;
using Exampler_ERP.Utilities;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using Exampler_ERP.Hubs;
using Microsoft.AspNetCore.SignalR;
using OfficeOpenXml;
using Microsoft.Extensions.Localization;

namespace Exampler_ERP.Controllers.Finance.MasterInfo
{
  public class CashAgainstSaleController : PositionController
  {
    private readonly AppDBContext _appDBContext;
    private readonly IStringLocalizer<CashAgainstSaleController> _localizer;
    private readonly IConfiguration _configuration;
    private readonly Utils _utils;
    private readonly IHubContext<NotificationHub> _hubContext;


    public CashAgainstSaleController(AppDBContext appDBContext, IConfiguration configuration, Utils utils, IHubContext<NotificationHub> hubContext, IStringLocalizer<CashAgainstSaleController> localizer) 
    : base(appDBContext)
    {
      _appDBContext = appDBContext;
      _configuration = configuration;
      _utils = utils;
      _hubContext = hubContext;
      _localizer = localizer;

    }
    public async Task<IActionResult> Index(string searchBranchName)
    {
      var CashAgainstSalesQuery = _appDBContext.Settings_CashAgainstSales
          .Include(b => b.BranchType)
          .Include(b => b.HeadofAccount_Five)
          .Where(b => b.DeleteYNID != 1);

      if (!string.IsNullOrEmpty(searchBranchName))
      {
        CashAgainstSalesQuery = CashAgainstSalesQuery.Where(b => b.BranchType.BranchTypeName.Contains(searchBranchName));
      }

      var CashAgainstSales = await CashAgainstSalesQuery.ToListAsync();

      if (!string.IsNullOrEmpty(searchBranchName) && CashAgainstSales.Count == 0)
      {
        await _hubContext.Clients.All.SendAsync("ReceiveSuccessFalse", "No Branch Name found with the name '" + searchBranchName + "'. Please check the name and try again.");
      }
      return View("~/Views/Finance/MasterInfo/CashAgainstSale/CashAgainstSale.cshtml", CashAgainstSales);
    }


    public async Task<IActionResult> CashAgainstSale()
    {
      var CashAgainstSales = await _appDBContext.Settings_CashAgainstSales.ToListAsync();
      return Ok(CashAgainstSales);
    }// Add the Edit action
    public async Task<IActionResult> Edit(int id)
    {
      ViewBag.BranchList = await _utils.GetBranchs();
      ViewBag.FiveList = await _utils.GetHeadofAccount_Five();
      ViewBag.ActiveYNIDList = await _utils.GetActiveYNIDList();
      var CashAgainstSale = await _appDBContext.Settings_CashAgainstSales.FindAsync(id);
      if (CashAgainstSale == null)
      {
        return NotFound();
      }
      return PartialView("~/Views/Finance/MasterInfo/CashAgainstSale/EditCashAgainstSale.cshtml", CashAgainstSale);
    }

    [HttpPost]
    public async Task<IActionResult> Edit(Settings_CashAgainstSale CashAgainstSale)
    {
      if (ModelState.IsValid)
      {

        _appDBContext.Update(CashAgainstSale);
        await _appDBContext.SaveChangesAsync();
        await _hubContext.Clients.All.SendAsync("ReceiveSuccessTrue", "Cash Against Sale Account connected updated successfully.");
        return Json(new { success = true });
      }
      return Json(new { success = false, message = "Error connecting Cash Against Sale Account. Please check the inputs." });
    }
    [HttpGet]
    public async Task<IActionResult> Create()
    {
      ViewBag.BranchList = await _utils.GetBranchs();
      ViewBag.FiveList = await _utils.GetHeadofAccount_Five();
      ViewBag.ActiveYNIDList = await _utils.GetActiveYNIDList();
      return PartialView("~/Views/Finance/MasterInfo/CashAgainstSale/AddCashAgainstSale.cshtml", new Settings_CashAgainstSale());
    }

    [HttpPost]
    public async Task<IActionResult> Create(Settings_CashAgainstSale CashAgainstSale)
    {
      if (ModelState.IsValid)
      {

        CashAgainstSale.DeleteYNID = 0;

        _appDBContext.Settings_CashAgainstSales.Add(CashAgainstSale);
        await _appDBContext.SaveChangesAsync();

        await _hubContext.Clients.All.SendAsync("ReceiveSuccessTrue", "Cash Against Sale Account connected successfully.");
        return Json(new { success = true });
      }

      return Json(new { success = false, message = "Error connecting Cash Against Sale Account. Please check the inputs." });
    }

    public async Task<IActionResult> Delete(int id)
    {
      var CashAgainstSale = await _appDBContext.Settings_CashAgainstSales.FindAsync(id);
      if (CashAgainstSale == null)
      {
        return NotFound();
      }

      CashAgainstSale.ActiveYNID = 2;
      CashAgainstSale.DeleteYNID = 1;

      _appDBContext.Settings_CashAgainstSales.Update(CashAgainstSale);
      await _appDBContext.SaveChangesAsync();
      await _hubContext.Clients.All.SendAsync("ReceiveSuccessTrue", "Cash Against Sale Account deleted successfully.");

      return Json(new { success = true });
    }
    public async Task<IActionResult> ExportToExcel()
    {
      ExcelPackage.LicenseContext = LicenseContext.NonCommercial;

      var CashAgainstSales = await _appDBContext.Settings_CashAgainstSales
          .Include(b => b.BranchType)
          .Include(b => b.HeadofAccount_Five)
          .Where(b => b.DeleteYNID != 1)
          .ToListAsync();

      using (var package = new ExcelPackage())
      {
        var worksheet = package.Workbook.Worksheets.Add(_localizer["lbl_CashAgainstSale"]);
        worksheet.Cells["A1"].Value = _localizer["lbl_BranchName"];
        worksheet.Cells["B1"].Value = _localizer["lbl_CashAgainstSaleAccount"];
        worksheet.Cells["C1"].Value = _localizer["lbl_Active"];


        for (int i = 0; i < CashAgainstSales.Count; i++)
        {
          worksheet.Cells[i + 2, 1].Value = CashAgainstSales[i].BranchType.BranchTypeName;
          worksheet.Cells[i + 2, 2].Value = CashAgainstSales[i].HeadofAccount_Five.HeadofAccount_FiveName;
          worksheet.Cells[i + 2, 3].Value = CashAgainstSales[i].ActiveYNID == 1 ? _localizer["lbl_Yes"] : _localizer["lbl_No"];
        }

        worksheet.Cells["A1:l1"].Style.Font.Bold = true;
        worksheet.Cells.AutoFitColumns();

        var stream = new MemoryStream();
        package.SaveAs(stream);
        stream.Position = 0;
        string excelName = _localizer["lbl_CashAgainstSale"]+$"-{DateTime.Now.ToString("yyyyMMddHHmmssfff")}.xlsx";

        return File(stream, "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet", excelName);
      }
    }
    public async Task<IActionResult> Print()
    {
      var CashAgainstSales = await _appDBContext.Settings_CashAgainstSales
          .Include(b => b.BranchType)
          .Include(b => b.HeadofAccount_Five)
          .Where(b => b.DeleteYNID != 1)
          .ToListAsync();
      return View("~/Views/Finance/MasterInfo/CashAgainstSale/PrintCashAgainstSale.cshtml", CashAgainstSales);
    }


  }
}

Controllers/HR/MasterInfo/EmployeeRequestTypeApprovalSetupController.cs
using Exampler_ERP.Models.Temp;
using Exampler_ERP.Models;
using Exampler_ERP.Utilities;
using Microsoft.AspNetCore.Mvc;
using OfficeOpenXml;
using Microsoft.EntityFrameworkCore;
using Exampler_ERP.Hubs;
using Microsoft.AspNetCore.SignalR;
using Microsoft.Extensions.Localization;

namespace Exampler_ERP.Controllers.HR.MasterInfo
{
  public class EmployeeRequestTypeApprovalSetupController : PositionController
  {
    private readonly AppDBContext _appDBContext;
    private readonly IStringLocalizer<EmployeeRequestTypeApprovalSetupController> _localizer;
    private readonly IConfiguration _configuration;
    private readonly ILogger<EmployeeRequestTypeApprovalSetupController> _logger;
    private readonly Utils _utils;
    private readonly IHubContext<NotificationHub> _hubContext;

    public EmployeeRequestTypeApprovalSetupController(AppDBContext appDBContext, IConfiguration configuration, ILogger<EmployeeRequestTypeApprovalSetupController> logger, Utils utils, IHubContext<NotificationHub> hubContext, IStringLocalizer<EmployeeRequestTypeApprovalSetupController> localizer) 
    : base(appDBContext)
    {
      _appDBContext = appDBContext;
      _configuration = configuration;
      _logger = logger;
      _utils = utils;
      _hubContext = hubContext;
      _localizer = localizer;

    }
    public async Task<IActionResult> Index(string searchEmployeeRequestTypeName)
    {
      // Query for EmployeeRequest Types with an optional search filter
      var EmployeeRequestTypesQuery = _appDBContext.Settings_EmployeeRequestTypes.AsQueryable();

      if (!string.IsNullOrEmpty(searchEmployeeRequestTypeName))
      {
        EmployeeRequestTypesQuery = EmployeeRequestTypesQuery
            .Where(pt => pt.EmployeeRequestTypeName.Contains(searchEmployeeRequestTypeName));
      }

      var EmployeeRequestTypes = await EmployeeRequestTypesQuery.ToListAsync();
      var EmployeeRequestTypeApprovalSetup = await _appDBContext.HR_EmployeeRequestTypeApprovalSetups.ToListAsync();

      // Create ViewModel based on query results
      var viewModel = new EmployeeRequestTypeApprovalSetupListViewModel
      {
        EmployeeRequestTypesWithRankCount = EmployeeRequestTypes.Select(pt => new EmployeeRequestTypeWithRankCountViewModel
        {
          EmployeeRequestTypeID = pt.EmployeeRequestTypeID,
          EmployeeRequestTypeName = pt.EmployeeRequestTypeName,
          RankCount = EmployeeRequestTypeApprovalSetup.Count(ptf => ptf.EmployeeRequestTypeID == pt.EmployeeRequestTypeID)
        }).ToList()
      };

      if (!string.IsNullOrEmpty(searchEmployeeRequestTypeName) && viewModel.EmployeeRequestTypesWithRankCount.Count == 0)
      {
        await _hubContext.Clients.All.SendAsync("ReceiveSuccessFalse", "No Employee Request Type found with the name '" + searchEmployeeRequestTypeName + "'. Please check the name and try again.");
      }

      return View("~/Views/HR/MasterInfo/EmployeeRequestTypeApprovalSetup/EmployeeRequestTypeApprovalSetup.cshtml", viewModel);
    }


    public async Task<IActionResult> EmployeeRequestTypeApprovalSetup()
    {
      var EmployeeRequestTypeApprovalSetups = await _appDBContext.HR_EmployeeRequestTypeApprovalSetups.ToListAsync();
      return Ok(EmployeeRequestTypeApprovalSetups);
    }
    public async Task<IActionResult> Edit(int id)
    {
      var EmployeeRequestTypeApprovalSetups = await _appDBContext.HR_EmployeeRequestTypeApprovalSetups
       .Where(pt => pt.EmployeeRequestTypeID == id)
       .Include(pt => pt.EmployeeRequestType)
       .Include(pt => pt.RoleType)
       .ToListAsync();

      if (EmployeeRequestTypeApprovalSetups == null || !EmployeeRequestTypeApprovalSetups.Any())
      {
        var EmployeeRequestType = await _appDBContext.Settings_EmployeeRequestTypes
            .Where(p => p.EmployeeRequestTypeID == id)
            .FirstOrDefaultAsync();

        if (EmployeeRequestType != null)
        {
          EmployeeRequestTypeApprovalSetups = new List<HR_EmployeeRequestTypeApprovalSetup>
            {
                new HR_EmployeeRequestTypeApprovalSetup
                {
                    EmployeeRequestTypeID = EmployeeRequestType.EmployeeRequestTypeID,
                    EmployeeRequestType = EmployeeRequestType
                }
            };
        }
        else
        {
          return NotFound(); // Or handle accordingly if EmployeeRequestType is not found
        }
      }

      ViewBag.RoleList = await _appDBContext.Settings_RoleTypes
          .Select(r => new { Value = r.RoleTypeID, Text = r.RoleTypeName })
          .ToListAsync();

      ViewBag.EmployeeRequestTypes = await _appDBContext.Settings_EmployeeRequestTypes.ToListAsync();

      return PartialView("~/Views/HR/MasterInfo/EmployeeRequestTypeApprovalSetup/EditEmployeeRequestTypeApprovalSetup.cshtml", EmployeeRequestTypeApprovalSetups);
    }



    [HttpPost]
    public async Task<IActionResult> Edit(List<HR_EmployeeRequestTypeApprovalSetup> EmployeeRequestTypeApprovalSetups)
    {
      foreach (var setup in EmployeeRequestTypeApprovalSetups)
      {
        _logger.LogInformation("Received Setup: ID={ID}, Rank={Rank}, RoleID={RoleID}", setup.EmployeeRequestTypeApprovalSetupID, setup.Rank, setup.RoleTypeID);
      }

      if (EmployeeRequestTypeApprovalSetups == null || EmployeeRequestTypeApprovalSetups.Count == 0)
      {
        await _hubContext.Clients.All.SendAsync("ReceiveSuccessFalse", "No data received.");
        _logger.LogWarning("No data received for edit.");
        return Json(new { success = false });
      }

      if (ModelState.IsValid)
      {
        try
        {
          var EmployeeRequestTypeId = EmployeeRequestTypeApprovalSetups.FirstOrDefault()?.EmployeeRequestTypeID;
          if (EmployeeRequestTypeId == null)
          {
            await _hubContext.Clients.All.SendAsync("ReceiveSuccessFalse", "Invalid EmployeeRequestTypeID.");
            return BadRequest("Invalid EmployeeRequestTypeID.");
          }

          var existingRecords = await _appDBContext.HR_EmployeeRequestTypeApprovalSetups
                                        .Where(p => p.EmployeeRequestTypeID == EmployeeRequestTypeId)
                                        .ToListAsync();

          _appDBContext.HR_EmployeeRequestTypeApprovalSetups.RemoveRange(existingRecords);

          foreach (var setup in EmployeeRequestTypeApprovalSetups)
          {
            if (setup.RoleTypeID != 0 && setup.Rank != 0)
            {
              _appDBContext.HR_EmployeeRequestTypeApprovalSetups.Add(setup);
            }
          }

          await _appDBContext.SaveChangesAsync();
          await _hubContext.Clients.All.SendAsync("ReceiveSuccessTrue", "Employee Request Type Approval Setup Update successfully.");
          return Json(new { success = true });
        }
        catch (Exception ex)
        {
          await _hubContext.Clients.All.SendAsync("ReceiveSuccessFalse", "An error occurred while updating the data.");
          _logger.LogError(ex, "Error updating EmployeeRequestTypeApprovalSetups");
          return Json(new { success = false });
        }
      }

      var errors = ModelState.Values.SelectMany(v => v.Errors);
      return PartialView("~/Views/HR/MasterInfo/EmployeeRequestTypeApprovalSetup/EditEmployeeRequestTypeApprovalSetup.cshtml", EmployeeRequestTypeApprovalSetups);
    }



    [HttpPost]
    public IActionResult Delete(int id)
    {
      var setups = _appDBContext.HR_EmployeeRequestTypeApprovalSetups
          .Where(x => x.EmployeeRequestTypeID == id)
          .ToList();

      if (setups == null || setups.Count == 0)
      {
        return Json(new { success = false, message = "Setup not found" });
      }

      _appDBContext.HR_EmployeeRequestTypeApprovalSetups.RemoveRange(setups);
      _appDBContext.SaveChanges();
      _hubContext.Clients.All.SendAsync("ReceiveSuccessTrue", "Employee Request Type Approval Setups deleted successfully.");
      return Json(new { success = true });
    }



    public async Task<IActionResult> ExportToExcel()
    {
      ExcelPackage.LicenseContext = LicenseContext.NonCommercial;

      var EmployeeRequestTypeApprovalSetups = await _appDBContext.HR_EmployeeRequestTypeApprovalSetups
      .Distinct()
      .Include(d => d.EmployeeRequestType) // Eagerly load the related Branch data
      .ToListAsync();


      using (var package = new ExcelPackage())
      {
        var worksheet = package.Workbook.Worksheets.Add(_localizer["lbl_EmployeeRequestTypeApprovalSetup"]);
        worksheet.Cells["A1"].Value = _localizer["lbl_EmployeeRequestTypeApprovalSetupID"];
        worksheet.Cells["B1"].Value = _localizer["lbl_EmployeeRequestTypeName"];
        worksheet.Cells["C1"].Value = _localizer["lbl_Rank"];
        worksheet.Cells["D1"].Value = _localizer["lbl_RoleType"];


        for (int i = 0; i < EmployeeRequestTypeApprovalSetups.Count; i++)
        {
          worksheet.Cells[i + 2, 1].Value = EmployeeRequestTypeApprovalSetups[i].EmployeeRequestTypeApprovalSetupID;
          worksheet.Cells[i + 2, 2].Value = EmployeeRequestTypeApprovalSetups[i].EmployeeRequestType?.EmployeeRequestTypeName;
          worksheet.Cells[i + 2, 3].Value = EmployeeRequestTypeApprovalSetups[i].Rank;
          worksheet.Cells[i + 2, 4].Value = EmployeeRequestTypeApprovalSetups[i].RoleTypeID;
        }

        worksheet.Cells["A1:l1"].Style.Font.Bold = true;
        worksheet.Cells.AutoFitColumns();

        var stream = new MemoryStream();
        package.SaveAs(stream);
        stream.Position = 0;
        string excelName = _localizer["lbl_EmployeeRequestTypeApprovalSetup"]+$"-{DateTime.Now.ToString("yyyyMMddHHmmssfff")}.xlsx";

        return File(stream, "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet", excelName);
      }
    }
    public async Task<IActionResult> Print()
    {
      var EmployeeRequestTypeApprovalSetups = await _appDBContext.HR_EmployeeRequestTypeApprovalSetups
      .Distinct()

Views/HR/MasterInfo/EmployeeRequestTypeApprovalSetup/EmployeeRequestTypeApprovalSetup.cshtml
@model Exampler_ERP.Models.Temp.EmployeeRequestTypeApprovalSetupListViewModel
@using Microsoft.AspNetCore.Mvc.Localization
@inject IViewLocalizer Localizer


@{
	ViewData["Title"] = @Localizer["lbl_MasterInformation"] + " - " + @Localizer["lbl_EmployeeRequestApprovalSetup"];
}

@section PageScripts {

    <script>
        $(document).ready(function () {
			 $('#EmployeeRequestTypeApprovalSetupListContainer').on('click', '.editEmployeeRequestTypeApprovalSetupLink', function (e) {
                e.preventDefault();
                var EmployeeRequestTypeId = $(this).data('id');
                $.get('@Url.Action("Edit", "EmployeeRequestTypeApprovalSetup")', { id: EmployeeRequestTypeId }, function (data) {
                    $('#editEmployeeRequestTypeApprovalSetupModalContainer').html(data);
                    $('#editEmployeeRequestTypeApprovalSetupModal').modal('show');
                });
            });

            $('#editEmployeeRequestTypeApprovalSetupModalContainer').on('click', '#saveChanges', function () {
                var formData = $('#editEmployeeRequestTypeApprovalSetupForm').serialize();
                console.log("Serialized form data:", formData); // Log serialized data for debugging
                $.post('@Url.Action("Edit", "EmployeeRequestTypeApprovalSetup")', formData, function (response) {
				   if (response.success) {
							$('#editEmployeeRequestTypeApprovalSetupModal').modal('hide');

							// ✅ Ab poora list AJAX se reload karo
							$.get('@Url.Action("Index", "EmployeeRequestTypeApprovalSetup")', function (partialHtml) {
								var html = $(partialHtml).find('#EmployeeRequestTypeApprovalSetupListContainer').html();
								$('#EmployeeRequestTypeApprovalSetupListContainer').html(html);
							});
						}
                });
            });

            // Close Modal Edit Contrainer
            $('#editEmployeeRequestTypeApprovalSetupModalContainer').on('click', '#Close', function () {
                $('#editEmployeeRequestTypeApprovalSetupModal').modal('hide'); // Close the modal directly
                // Additional logic if needed
            });


            // Delete EmployeeRequestTypeApprovalSetup
			 $('#EmployeeRequestTypeApprovalSetupListContainer').on('click', '.deleteEmployeeRequestTypeApprovalSetupLink', function (e) {
                e.preventDefault();
                var EmployeeRequestTypeApprovalSetupId = $(this).data('id');
                $.post('@Url.Action("Delete", "EmployeeRequestTypeApprovalSetup")', { id: EmployeeRequestTypeApprovalSetupId }, function (response) {
					 if (response.success) {
					$.get('@Url.Action("Index", "EmployeeRequestTypeApprovalSetup")', function (partialHtml) {
					  var html = $(partialHtml).find('#EmployeeRequestTypeApprovalSetupListContainer').html();
					  $('#EmployeeRequestTypeApprovalSetupListContainer').html(html);
					});
				  }
                });
            });

            // Print functionality
            $('#printButton').click(function () {
                window.print();
            });
        });
    </script>
    <script>
        function printEmployeeRequestTypeApprovalSetups() {
            var printWindow = window.open('@Url.Action("Print", "EmployeeRequestTypeApprovalSetup")', '_blank');
            printWindow.focus();
        }
        $('#searchEmployeeRequestTypeButton').click(function () {
            var searchValue = $('#searchEmployeeRequestTypeInput').val();
			$.get('@Url.Action("Index", "EmployeeRequestTypeApprovalSetup")', { searchEmployeeRequestTypeName: searchValue }, function (partialHtml) {
				var html = $(partialHtml).find('#EmployeeRequestTypeApprovalSetupListContainer').html();
				$('#EmployeeRequestTypeApprovalSetupListContainer').html(html);
			});
		});
    </script>
}
<h4 class="py-3 mb-4">
	<span class="text-muted fw-light">@Localizer["lbl_MasterInformation"] /</span> @Localizer["lbl_EmployeeRequestApprovalSetup"]
</h4>
<div class="row">
    <div class="col-md-12">

        <div class="card">
            <h5 class="card-header">@Localizer["lbl_SearchingBox"]</h5>
            <div class="Searching-Box-padding">
                <div class="row mb-4">
                    <div class="col-md-8" style="padding-bottom: 15px;">
                        <!-- Search Field and Button -->
                        <div class="input-group">
                            <input type="text" class="form-control" placeholder="@Localizer["lbl_SearchEmployeeRequestTypeName"]" id="searchEmployeeRequestTypeInput">
                            <button class="btn btn-outline-secondary" type="button" id="searchEmployeeRequestTypeButton">
                                <i class="fa fa-search"></i>
                            </button>
                        </div>
                    </div>
                    <div class="col-md-4 text-end">
                        <!-- Action Buttons -->
                        <button type="button" class="btn btn-outline-secondary" onclick="location.href='@Url.Action("ExportToExcel", "EmployeeRequestTypeApprovalSetup")'">@Localizer["lbl_Excel"]</button>
                        <button type="button" class="btn btn-outline-secondary" onclick="printEmployeeRequestTypeApprovalSetups()">@Localizer["lbl_Print"]</button>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
<br />
<div class="row">
    <div class="col-md-12">
        <div class="card">
			<h5 class="card-header">@Localizer["lbl_EmployeeRequestTypeApprovalSetupList"]</h5>
            <div class="">
                <div class="col-lg-12 col-md-12 col-sm-12 mb-12 SmallHide GVHeader">
                    <div class="row">
                        <div class="col-10 col-md-10 col-lg-10">
                            <div class="row">
                                <div class="col-8">
                                    <p class="text-nowrap">@Localizer["lbl_EmployeeRequestTypeName"]</p>
                                </div>
                                <div class="col-2">
                                    <p class="text-nowrap">@Localizer["lbl_TotalRank"]</p>
                                </div>
                            </div>
                        </div>
                        <div class="col-2 col-md-2 col-lg-2">
                            <div class="row">
                                <div class="col-6">
                                    <p class="text-nowrap">@Localizer["lbl_Edit"]</p>
                                </div>
                                <div class="col-6">
                                    <p class="text-nowrap">@Localizer["lbl_Delete"]</p>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
				<div id="EmployeeRequestTypeApprovalSetupListContainer">
					@Html.Partial("~/Views/HR/MasterInfo/EmployeeRequestTypeApprovalSetup/_EmployeeRequestTypeApprovalSetupListPartial.cshtml", Model)
				</div>
            </div>
        </div>
    </div>
</div>


<!-- Include the modal partial -->
<div id="editEmployeeRequestTypeApprovalSetupModalContainer"></div>

Views/HR/MasterInfo/EmployeeRequestTypeApprovalSetup/PrintEmployeeRequestTypeApprovalSetup.cshtml
@model IEnumerable<Exampler_ERP.Models.HR_EmployeeRequestTypeApprovalSetup>
@using Microsoft.AspNetCore.Mvc.Localization
@inject IViewLocalizer Localizer
@{
    Layout = "_PrintLayout";
}
<!DOCTYPE html>
<html>
<head>
	<title>@Localizer["lbl_PrintEmployeeRequestTypeApprovalSetup"]</title>
    <style>
        table {
            width: 100%;
            border-collapse: collapse;
            background-color: white;
        }

        table, th, td {
            border: 1px solid black;
        }

        th, td {
            padding: 8px;
            text-align: left;
        }

        th {
            background-color: white;
        }
    </style>
</head>
<body style="background-color:white">
	<h2>@Localizer["lbl_EmployeeRequestTypeApprovalSetupList"]</h2>
    <table>
        <thead>
            <tr>
				<th>@Localizer["lbl_EmployeeRequestTypeApprovalSetupID"]</th>
                <th>@Localizer["lbl_EmployeeRequestTypeName"]</th>
				<th>@Localizer["lbl_Rank"]</th>
                <th>@Localizer["lbl_RoleType"]</th>
            </tr>
        </thead>
        <tbody>
            @foreach (var EmployeeRequestTypeApprovalSetup in Model)
            {
                <tr>
                    <td>@EmployeeRequestTypeApprovalSetup.EmployeeRequestTypeApprovalSetupID</td>
                    <td>@(EmployeeRequestTypeApprovalSetup.EmployeeRequestType?.EmployeeRequestTypeName ?? "N/A")</td>
                    <td>@EmployeeRequestTypeApprovalSetup.Rank</td>
                    <td>@EmployeeRequestTypeApprovalSetup.RoleTypeID</td>
                </tr>
            }
        </tbody>
    </table>
    <script>
        window.print();
    </script>
</body>
</html>